// auto_describe_pr: generate a PR's title and description from its full diff with an
// OpenAI-compatible chat model (the user-hosted LiteLLM proxy by default). The title is replaced
// only when the model judges the existing one to be a missing/autogenerated placeholder; the
// description is rewritten on every new diff (the old one is passed to the model so human-written
// notes that are still accurate survive the rewrite).
import type { Env } from './worker';
import type { Logger } from './logger';
import type { PrMinderConfig } from './config';
import { getPullDiff, updatePullText } from './github';
import { describedDiffHash, markDescribed } from './state';

// Production values for the endpoint live in wrangler.toml [vars] (AI_BASE_URL / AI_MODEL);
// these are the fallback so dev and tests work without them. The API key is always the
// AI_API_KEY secret — without it the feature logs a skip and does nothing.
export const DEFAULT_AI_BASE_URL = 'https://litellm.pazer.ai/v1';
export const DEFAULT_AI_MODEL = 'auto-pr-desccript';

// A diff larger than this is truncated before being sent to the model — enough for any PR a
// description meaningfully summarizes, and a guard against blowing the model's context window.
const MAX_DIFF_CHARS = 200_000;
// Hard cap on one model call. The webhook path runs this via waitUntil, whose post-response
// grace is ~30s, so in practice the platform bounds it sooner; this is the safety net for
// other contexts so a hung upstream can never pin an invocation.
const AI_TIMEOUT_MS = 60_000;

// The response contract given to the model. Kept to exactly the three fields the worker acts on
// (the description is always rewritten, so its "was valid" classification would be unused).
const PR_METADATA_RESPONSE_XSD = `<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="prMetadata">
    <xs:complexType>
      <xs:all>
        <xs:element name="oldTitleWasValid" type="xs:boolean"/>
        <xs:element name="suggestedTitle" type="xs:string"/>
        <xs:element name="suggestedDescription" type="xs:string"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>`;

const SYSTEM_PROMPT =
  'You write GitHub pull request metadata from a unified diff. ' +
  'First classify whether the existing PR title is meaningfully populated. ' +
  "Autogenerated placeholder text means things like 'update', 'changes', 'claude update thingy 379491', branch-like junk, or ticket-only titles. " +
  'Autogenerated does not mean AI-generated prose. ' +
  'Then write replacement metadata from the diff. ' +
  'The suggested title should be specific and under 72 characters when possible. ' +
  'The suggested description should be Markdown with a short summary and practical test/risk notes when inferable. Do not invent test results. ' +
  'The existing description is included; carry forward any of its information that is still accurate. ' +
  `Return only XML matching this XSD, with no prose, no markdown code fences, and no attributes on any element:\n${PR_METADATA_RESPONSE_XSD}`;

export interface PrMetadataSuggestion {
  oldTitleWasValid: boolean;
  suggestedTitle: string;
  suggestedDescription: string;
}

// Which pull_request actions warrant (re)describing. opened = a new PR; synchronize = new
// commits (including pr-minder's own update-branch merge — the diff-hash dedup below makes that
// a no-op unless the effective diff actually changed); ready_for_review = a PR that was opened
// as a draft becoming real (drafts are skipped wholesale in onPR, so this is the first time we
// can see it). Our own zombie close+reopen comes back as `reopened`, which is deliberately not
// listed — the PR was already described from its original opened/synchronize event.
export function shouldDescribe(action: string): boolean {
  return ['opened', 'ready_for_review', 'synchronize'].includes(action);
}

// Describe one PR: fetch its full diff, ask the model for metadata, PATCH the PR. Deduped on the
// SHA-256 of the diff via KV — a synchronize whose effective diff is unchanged (the common case
// for pr-minder's own update-branch merges) costs one GitHub call and zero model calls. The hash
// is recorded only after a successful PATCH, so any failure leaves the marker untouched and the
// next event retries. Throws on failure; the caller logs and swallows (a describe failure must
// never fail the webhook).
export async function maybeDescribePr(env: Env, repo: string, pr: any, config: PrMinderConfig, token: string, log: Logger): Promise<void> {
  const tag = `${repo}#${pr.number}`;
  if (!env.AI_API_KEY) {
    log.log(`${tag}: skip describe (AI_API_KEY secret not set)`);
    return;
  }

  const fullDiff = await getPullDiff(repo, pr.number, token, log);
  if (!fullDiff || !fullDiff.trim()) {
    log.log(`${tag}: skip describe (no diff)`);
    return;
  }
  const diff = fullDiff.length > MAX_DIFF_CHARS
    ? `${fullDiff.slice(0, MAX_DIFF_CHARS)}\n... (diff truncated at ${MAX_DIFF_CHARS} characters)`
    : fullDiff;

  const hash = await sha256Hex(diff);
  if (env.PR_STATE && (await describedDiffHash(env.PR_STATE, repo, pr.number)) === hash) {
    log.log(`${tag}: skip describe (diff unchanged)`);
    return;
  }

  const meta = await generatePrMetadata(env, config, { title: pr.title ?? '', body: pr.body ?? '' }, diff, log);

  const fields: { title?: string; body?: string } = {};
  if (!meta.oldTitleWasValid && meta.suggestedTitle) fields.title = meta.suggestedTitle;
  if (meta.suggestedDescription) fields.body = meta.suggestedDescription;
  if (!fields.title && !fields.body) {
    log.log(`${tag}: skip describe (model returned nothing usable)`);
    return;
  }

  log.log(`${tag}: describe -> ${Object.keys(fields).join('+')} (title was ${meta.oldTitleWasValid ? 'valid' : 'placeholder'})`);
  await updatePullText(repo, pr.number, fields, token, log);
  if (env.PR_STATE) await markDescribed(env.PR_STATE, repo, pr.number, hash);
}

// One chat-completions call (temperature 0 so identical input yields identical metadata), parsed
// into the three fields. The existing title/description ride along in the user message so the
// model can both classify the title and preserve still-accurate description content.
export async function generatePrMetadata(
  env: Env,
  config: PrMinderConfig,
  existing: { title: string; body: string },
  diff: string,
  log: Logger,
): Promise<PrMetadataSuggestion> {
  const baseUrl = (env.AI_BASE_URL || DEFAULT_AI_BASE_URL).replace(/\/+$/, '');
  const model = config.autoDescribePr.model || env.AI_MODEL || DEFAULT_AI_MODEL;
  const existingJson = JSON.stringify({ title: existing.title, description: existing.body.trim() }, null, 2);

  const r = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${env.AI_API_KEY}` },
    body: JSON.stringify({
      model,
      temperature: 0,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: `Existing PR metadata:\n${existingJson}\n\nGenerate PR metadata for this diff:\n\n${diff}` },
      ],
    }),
    signal: AbortSignal.timeout(AI_TIMEOUT_MS),
  });
  if (!r.ok) {
    const body = await r.text();
    log.log(`describe: AI request failed (${r.status}) model=${model}`);
    throw new Error(`AI request failed (${r.status}): ${body.slice(0, 500)}`);
  }
  const data: any = await r.json();
  const content = data?.choices?.[0]?.message?.content;
  if (typeof content !== 'string' || !content) throw new Error('AI response did not include message content');
  return parsePrMetadataResponse(content);
}

// Parse the model's XML reply leniently. Models routinely take liberties with "return only this
// XML": invented attributes on elements (a live failure was `<suggestedDescription la="markdown">`),
// a dropped <prMetadata> wrapper, code fences around the document, entity-escaped content. The
// extraction regexes therefore allow attributes and search the whole reply, and entities are
// decoded. suggestedDescription is the one hard requirement (it's always applied); a missing or
// garbled oldTitleWasValid fails safe to "valid", i.e. the existing title is left alone.
export function parsePrMetadataResponse(content: string): PrMetadataSuggestion {
  const scope = tryExtractTagged(content, 'prMetadata') ?? content;
  const suggestedDescription = tryExtractTagged(scope, 'suggestedDescription');
  if (suggestedDescription === null) throw new Error('AI response did not include <suggestedDescription>');
  const suggestedTitle = tryExtractTagged(scope, 'suggestedTitle') ?? '';
  const oldTitleWasValid = (tryExtractTagged(scope, 'oldTitleWasValid') ?? '').trim().toLowerCase() !== 'false';
  return { oldTitleWasValid, suggestedTitle, suggestedDescription };
}

// The content between <tag ...> and </tag>, or null when absent. Case-insensitive, tolerates
// attributes on the opening tag and whitespace in the closing one, decodes XML entities.
function tryExtractTagged(text: string, tag: string): string | null {
  const match = new RegExp(`<${tag}(?:\\s[^>]*)?>\\s*([\\s\\S]*?)\\s*</${tag}\\s*>`, 'i').exec(text);
  return match ? unescapeXml(match[1].trim()) : null;
}

// Decode the XML entities a model may emit inside element content (named + numeric forms).
function unescapeXml(text: string): string {
  return text.replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos);/gi, (entity, value: string) => {
    const normalized = value.toLowerCase();
    if (normalized === 'amp') return '&';
    if (normalized === 'lt') return '<';
    if (normalized === 'gt') return '>';
    if (normalized === 'quot') return '"';
    if (normalized === 'apos') return "'";
    const codePoint = normalized.startsWith('#x')
      ? Number.parseInt(normalized.slice(2), 16)
      : Number.parseInt(normalized.slice(1), 10);
    return Number.isFinite(codePoint) ? String.fromCodePoint(codePoint) : entity;
  });
}

async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}
